[package]
name = "egg"
version = "0.1.0"
edition = "2021"
authors = ["Dr. Ralf Berger <dr.ralf.berger@gmail.com>"]
description = "Simple command line tool to create a short time timer. Plays a sound, if time is up."

[dependencies]
soloud = "1"
regex = "1"
thiserror = "1"
chrono = "0.4"
